#!/usr/bin/env python3
#
# pyright: reportOperatorIssue=false
"""
Generate manufactured-solution expressions for the 2D conjugate heat transfer
project.

The script emits:
  - a C++ header-style snippet with analytic fields, boundary values, and RHS
  - a concise LaTeX report with the same expressions in mathematical form

Model assumed:
  - steady incompressible Navier-Stokes in 2D
  - steady advection-diffusion temperature equation

The velocity, pressure and temperature fields are:
  u = (sin(pi x) cos(pi y), -cos(pi x) sin(pi y))
  p = cos(pi x) sin(pi y)
  T = cos(2 pi x) sin(pi y)
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import sympy as sp


@dataclass(frozen=True)
class ExprSet:
    u: tuple[sp.Expr, sp.Expr]
    p: sp.Expr
    T: sp.Expr
    momentum_rhs: tuple[sp.Expr, sp.Expr]
    continuity_rhs: sp.Expr
    temperature_rhs: sp.Expr


def build_expressions():
    x, y, nu, kappa = sp.symbols("x y nu kappa", real=True)
    pi = sp.pi

    u = (
        sp.sin(pi * x) * sp.cos(pi * y),
        -sp.cos(pi * x) * sp.sin(pi * y),
    )
    p = sp.cos(pi * x) * sp.sin(pi * y)
    T = sp.cos(2 * pi * x) * sp.sin(pi * y)

    ux, uy = u
    grad_u = [
        [sp.diff(ux, x), sp.diff(ux, y)],
        [sp.diff(uy, x), sp.diff(uy, y)],
    ]
    lap_u = [sp.diff(ux, x, 2) + sp.diff(ux, y, 2), sp.diff(uy, x, 2) + sp.diff(uy, y, 2)]
    grad_p = (sp.diff(p, x), sp.diff(p, y))
    adv_u = (
        ux * grad_u[0][0] + uy * grad_u[0][1],
        ux * grad_u[1][0] + uy * grad_u[1][1],
    )
    momentum_rhs = tuple(sp.simplify(adv_u[i] - nu * lap_u[i] + grad_p[i]) for i in range(2))
    continuity_rhs = sp.simplify(sp.diff(ux, x) + sp.diff(uy, y))

    grad_T = (sp.diff(T, x), sp.diff(T, y))
    lap_T = sp.diff(T, x, 2) + sp.diff(T, y, 2)
    adv_T = ux * grad_T[0] + uy * grad_T[1]
    temperature_rhs = sp.simplify(adv_T - kappa * lap_T)

    return ExprSet(
        u=u,
        p=p,
        T=T,
        momentum_rhs=momentum_rhs,
        continuity_rhs=continuity_rhs,
        temperature_rhs=temperature_rhs,
    ), (x, y, nu, kappa)


def cxx(expr: sp.Expr) -> str:
    return sp.ccode(sp.simplify(expr))


def boundary_values(expr: sp.Expr, x: sp.Symbol, y: sp.Symbol):
    return {
        "x = 0": sp.simplify(expr.subs(x, 0)),
        "x = 1": sp.simplify(expr.subs(x, 1)),
        "y = 0": sp.simplify(expr.subs(y, 0)),
        "y = 1": sp.simplify(expr.subs(y, 1)),
    }


def write_cpp(path: Path, exprs: ExprSet, x, y, nu, kappa):
    lines = []
    lines.append("// Auto-generated by scripts/generate_mms.py")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cmath>")
    lines.append("")
    lines.append("namespace mms {")
    lines.append("inline double velocity_x(const double x, const double y) { return " + cxx(exprs.u[0]) + "; }")
    lines.append("inline double velocity_y(const double x, const double y) { return " + cxx(exprs.u[1]) + "; }")
    lines.append("inline double pressure(const double x, const double y) { return " + cxx(exprs.p) + "; }")
    lines.append("inline double temperature(const double x, const double y) { return " + cxx(exprs.T) + "; }")
    lines.append("")
    lines.append("inline double momentum_rhs_x(const double x, const double y, const double nu) {")
    lines.append("  return " + cxx(exprs.momentum_rhs[0]) + ";")
    lines.append("}")
    lines.append("inline double momentum_rhs_y(const double x, const double y, const double nu) {")
    lines.append("  return " + cxx(exprs.momentum_rhs[1]) + ";")
    lines.append("}")
    lines.append("inline double continuity_rhs(const double x, const double y) { return " + cxx(exprs.continuity_rhs) + "; }")
    lines.append("inline double temperature_rhs(const double x, const double y, const double kappa) {")
    lines.append("  return " + cxx(exprs.temperature_rhs) + ";")
    lines.append("}")
    lines.append("")
    for name, field in [("u_x", exprs.u[0]), ("u_y", exprs.u[1]), ("p", exprs.p), ("T", exprs.T)]:
        values = boundary_values(field, x, y)
        for label, expr in values.items():
            fn = (
                "x0" if label == "x = 0" else
                "x1" if label == "x = 1" else
                "y0" if label == "y = 0" else
                "y1"
            )
            lines.append(f"inline double {name}_{fn}(const double x, const double y) {{ return {cxx(expr)}; }}")
        lines.append("")
    lines.append("} // namespace mms")
    lines.append("")

    path.write_text("\n".join(lines))


def latex_piece(name: str, expr: sp.Expr) -> str:
    return rf"\[{name}(x,y) = {sp.latex(sp.simplify(expr))}\]"


def write_latex(path: Path, exprs: ExprSet, x, y, nu, kappa):
    lines = []
    lines.append(r"\section*{Manufactured solution}")
    lines.append(r"This report defines a steady MMS pair on $\Omega=[0,1]\times[0,1]$.")
    lines.append("")
    lines.append(r"\subsection*{Exact fields}")
    lines.append(latex_piece(r"u_x", exprs.u[0]))
    lines.append(latex_piece(r"u_y", exprs.u[1]))
    lines.append(latex_piece(r"p", exprs.p))
    lines.append(latex_piece(r"T", exprs.T))
    lines.append("")
    lines.append(r"\subsection*{Governing equations}")
    lines.append(r"For momentum we assume the steady incompressible Navier--Stokes residual")
    lines.append(r"$ (u \cdot \nabla)u - \nu \Delta u + \nabla p - f = 0$, with $\nabla \cdot u = 0$.")
    lines.append(r"For temperature we assume steady advection--diffusion")
    lines.append(r"$u \cdot \nabla T - \kappa \Delta T - s = 0$.")
    lines.append("")
    lines.append(r"\subsection*{Source terms}")
    lines.append(latex_piece(r"f_x", exprs.momentum_rhs[0]))
    lines.append(latex_piece(r"f_y", exprs.momentum_rhs[1]))
    lines.append(r"\[" + r"\nabla \cdot u = " + sp.latex(exprs.continuity_rhs) + r"\]")
    lines.append(latex_piece(r"s", exprs.temperature_rhs))
    lines.append("")
    lines.append(r"\subsection*{Boundary values on $\partial\Omega$}")
    for name, field in [("$u_x$", exprs.u[0]), ("$u_y$", exprs.u[1]), ("$p$", exprs.p), ("$T$", exprs.T)]:
        lines.append(r"\paragraph*{" + name + "}")
        for label, val in boundary_values(field, x, y).items():
            lines.append(r"\[" + rf"{label}: " + sp.latex(sp.simplify(val)) + r"\]")
    path.write_text("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cpp-out", type=Path, default=Path("mms_generated.h"))
    parser.add_argument("--tex-out", type=Path, default=Path("mms_report.tex"))
    args = parser.parse_args()

    exprs, (x, y, nu, kappa) = build_expressions()
    write_cpp(args.cpp_out, exprs, x, y, nu, kappa)
    write_latex(args.tex_out, exprs, x, y, nu, kappa)


if __name__ == "__main__":
    main()
