#!/usr/bin/env python3
#
# pyright: reportOperatorIssue=false
"""
Generate C++ and LaTeX outputs from the shared MMS expressions.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parent))

import sympy as sp

from expressions_mms import ExprSet, boundary_values, build_expressions


def cxx(expr: sp.Expr) -> str:
    return sp.ccode(sp.simplify(expr))


def write_cpp(path: Path, exprs: ExprSet, x, y, nu, thermal_diffusivity):
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("// Auto-generated by scripts/generate_mms.py")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cmath>")
    lines.append("")
    lines.append("namespace mms {")
    lines.append("inline double velocity_x(const double x, const double y) { return " + cxx(exprs.u[0]) + "; }")
    lines.append("inline double velocity_y(const double x, const double y) { return " + cxx(exprs.u[1]) + "; }")
    lines.append("inline double pressure(const double x, const double y) { return " + cxx(exprs.p) + "; }")
    lines.append("inline double temperature(const double x, const double y) { return " + cxx(exprs.T) + "; }")
    lines.append("")
    lines.append("inline double grad_x_velocity_x(const double x, const double y) { return " + cxx(exprs.grad_u[0][0]) + "; }")
    lines.append("inline double grad_y_velocity_x(const double x, const double y) { return " + cxx(exprs.grad_u[0][1]) + "; }")
    lines.append("inline double grad_x_velocity_y(const double x, const double y) { return " + cxx(exprs.grad_u[1][0]) + "; }")
    lines.append("inline double grad_y_velocity_y(const double x, const double y) { return " + cxx(exprs.grad_u[1][1]) + "; }")
    lines.append("inline double grad_x_pressure(const double x, const double y) { return " + cxx(exprs.grad_p[0]) + "; }")
    lines.append("inline double grad_y_pressure(const double x, const double y) { return " + cxx(exprs.grad_p[1]) + "; }")
    lines.append("inline double grad_x_temperature(const double x, const double y) { return " + cxx(exprs.grad_T[0]) + "; }")
    lines.append("inline double grad_y_temperature(const double x, const double y) { return " + cxx(exprs.grad_T[1]) + "; }")
    lines.append("")
    lines.append("inline double momentum_rhs_x(const double x, const double y, const double nu) {")
    lines.append("  return " + cxx(exprs.momentum_rhs[0]) + ";")
    lines.append("}")
    lines.append("inline double momentum_rhs_y(const double x, const double y, const double nu) {")
    lines.append("  return " + cxx(exprs.momentum_rhs[1]) + ";")
    lines.append("}")
    lines.append("inline double continuity_rhs(const double x, const double y) { return " + cxx(exprs.continuity_rhs) + "; }")
    lines.append("inline double temperature_rhs(const double x, const double y, const double thermal_diffusivity) {")
    lines.append("  return " + cxx(exprs.temperature_rhs) + ";")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace mms")
    lines.append("")

    path.write_text("\n".join(lines))


def latex_piece(name: str, expr: sp.Expr, substitutions=None) -> str:
    if substitutions:
        expr = expr.xreplace(substitutions)
    return rf"\[{name}(x,y) = {sp.latex(sp.simplify(expr))}\]"


def write_latex(path: Path, exprs: ExprSet, x, y, nu, thermal_diffusivity):
    path.parent.mkdir(parents=True, exist_ok=True)

    latex_substitutions = {thermal_diffusivity: sp.Symbol("kappa")}

    lines = []
    lines.append(r"\section*{Manufactured solution}")
    lines.append(r"This report defines a steady MMS pair on $\Omega=[0,1]\times[0,1]$.")
    lines.append("")
    lines.append(r"\subsection*{Exact fields}")
    lines.append(latex_piece(r"u_x", exprs.u[0]))
    lines.append(latex_piece(r"u_y", exprs.u[1]))
    lines.append(latex_piece(r"p", exprs.p))
    lines.append(latex_piece(r"T", exprs.T))
    lines.append("")
    lines.append(r"\subsection*{Governing equations}")
    lines.append(r"For momentum we assume the steady incompressible Navier--Stokes residual")
    lines.append(r"$ (u \cdot \nabla)u - \nu \Delta u + \nabla p - f = 0$, with $\nabla \cdot u = 0$.")
    lines.append(r"For temperature we assume steady advection--diffusion")
    lines.append(r"$u \cdot \nabla T - \kappa \Delta T - s = 0$, where $\kappa$ is thermal diffusivity.")
    lines.append("")
    lines.append(r"\subsection*{Source terms}")
    lines.append(latex_piece(r"f_x", exprs.momentum_rhs[0]))
    lines.append(latex_piece(r"f_y", exprs.momentum_rhs[1]))
    lines.append(r"\[" + r"\nabla \cdot u = " + sp.latex(exprs.continuity_rhs) + r"\]")
    lines.append(latex_piece(r"s", exprs.temperature_rhs, latex_substitutions))
    lines.append("")
    lines.append(r"\subsection*{Boundary values on $\partial\Omega$}")
    for name, field in [("$u_x$", exprs.u[0]), ("$u_y$", exprs.u[1]), ("$p$", exprs.p), ("$T$", exprs.T)]:
        lines.append(r"\paragraph*{" + name + "}")
        for label, val in boundary_values(field, x, y).items():
            lines.append(r"\[" + rf"{label}: " + sp.latex(sp.simplify(val)) + r"\]")
    path.write_text("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument("--cpp-out", type=Path, default=Path("src/mms_generated.h"), help="Path to the generated C++ header")
    parser.add_argument("--tex-out", type=Path, default=Path("mms_report.tex"), help="Path to the generated LaTeX report")
    args = parser.parse_args()

    exprs, (x, y, nu, thermal_diffusivity) = build_expressions()
    write_cpp(args.cpp_out, exprs, x, y, nu, thermal_diffusivity)
    write_latex(args.tex_out, exprs, x, y, nu, thermal_diffusivity)


if __name__ == "__main__":
    main()
