#!/usr/bin/env python3
#
# pyright: reportOperatorIssue=false
"""
Generate C++ and LaTeX outputs from the shared MMS expressions.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parent))

import sympy as sp

from expressions_mms import ExprSet, boundary_values, build_expressions


def cxx(expr: sp.Expr) -> str:
    return sp.ccode(sp.simplify(expr))


def write_cpp(path: Path, exprs: ExprSet, x, y, nu, kappa):
    lines = []
    lines.append("// Auto-generated by scripts/generate_mms.py")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cmath>")
    lines.append("")
    lines.append("namespace mms {")
    lines.append("inline double velocity_x(const double x, const double y) { return " + cxx(exprs.u[0]) + "; }")
    lines.append("inline double velocity_y(const double x, const double y) { return " + cxx(exprs.u[1]) + "; }")
    lines.append("inline double pressure(const double x, const double y) { return " + cxx(exprs.p) + "; }")
    lines.append("inline double temperature(const double x, const double y) { return " + cxx(exprs.T) + "; }")
    lines.append("")
    lines.append("inline double momentum_rhs_x(const double x, const double y, const double nu) {")
    lines.append("  return " + cxx(exprs.momentum_rhs[0]) + ";")
    lines.append("}")
    lines.append("inline double momentum_rhs_y(const double x, const double y, const double nu) {")
    lines.append("  return " + cxx(exprs.momentum_rhs[1]) + ";")
    lines.append("}")
    lines.append("inline double continuity_rhs(const double x, const double y) { return " + cxx(exprs.continuity_rhs) + "; }")
    lines.append("inline double temperature_rhs(const double x, const double y, const double kappa) {")
    lines.append("  return " + cxx(exprs.temperature_rhs) + ";")
    lines.append("}")
    lines.append("")
    for name, field in [("u_x", exprs.u[0]), ("u_y", exprs.u[1]), ("p", exprs.p), ("T", exprs.T)]:
        values = boundary_values(field, x, y)
        for label, expr in values.items():
            fn = (
                "x0" if label == "x = 0" else
                "x1" if label == "x = 1" else
                "y0" if label == "y = 0" else
                "y1"
            )
            lines.append(f"inline double {name}_{fn}(const double x, const double y) {{ return {cxx(expr)}; }}")
        lines.append("")
    lines.append("} // namespace mms")
    lines.append("")

    path.write_text("\n".join(lines))


def latex_piece(name: str, expr: sp.Expr) -> str:
    return rf"\[{name}(x,y) = {sp.latex(sp.simplify(expr))}\]"


def write_latex(path: Path, exprs: ExprSet, x, y, nu, kappa):
    lines = []
    lines.append(r"\section*{Manufactured solution}")
    lines.append(r"This report defines a steady MMS pair on $\Omega=[0,1]\times[0,1]$.")
    lines.append("")
    lines.append(r"\subsection*{Exact fields}")
    lines.append(latex_piece(r"u_x", exprs.u[0]))
    lines.append(latex_piece(r"u_y", exprs.u[1]))
    lines.append(latex_piece(r"p", exprs.p))
    lines.append(latex_piece(r"T", exprs.T))
    lines.append("")
    lines.append(r"\subsection*{Governing equations}")
    lines.append(r"For momentum we assume the steady incompressible Navier--Stokes residual")
    lines.append(r"$ (u \cdot \nabla)u - \nu \Delta u + \nabla p - f = 0$, with $\nabla \cdot u = 0$.")
    lines.append(r"For temperature we assume steady advection--diffusion")
    lines.append(r"$u \cdot \nabla T - \kappa \Delta T - s = 0$.")
    lines.append("")
    lines.append(r"\subsection*{Source terms}")
    lines.append(latex_piece(r"f_x", exprs.momentum_rhs[0]))
    lines.append(latex_piece(r"f_y", exprs.momentum_rhs[1]))
    lines.append(r"\[" + r"\nabla \cdot u = " + sp.latex(exprs.continuity_rhs) + r"\]")
    lines.append(latex_piece(r"s", exprs.temperature_rhs))
    lines.append("")
    lines.append(r"\subsection*{Boundary values on $\partial\Omega$}")
    for name, field in [("$u_x$", exprs.u[0]), ("$u_y$", exprs.u[1]), ("$p$", exprs.p), ("$T$", exprs.T)]:
        lines.append(r"\paragraph*{" + name + "}")
        for label, val in boundary_values(field, x, y).items():
            lines.append(r"\[" + rf"{label}: " + sp.latex(sp.simplify(val)) + r"\]")
    path.write_text("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cpp-out", type=Path, default=Path("mms_generated.h"))
    parser.add_argument("--tex-out", type=Path, default=Path("mms_report.tex"))
    args = parser.parse_args()

    exprs, (x, y, nu, kappa) = build_expressions()
    write_cpp(args.cpp_out, exprs, x, y, nu, kappa)
    write_latex(args.tex_out, exprs, x, y, nu, kappa)


if __name__ == "__main__":
    main()
