// Auto-generated by scripts/generate_mms.py
#pragma once

#include <cmath>

namespace mms {
inline double velocity_x(const double x, const double y) { return sin(M_PI*x)*cos(M_PI*y); }
inline double velocity_y(const double x, const double y) { return -sin(M_PI*y)*cos(M_PI*x); }
inline double pressure(const double x, const double y) { return sin(M_PI*y)*cos(M_PI*x); }
inline double temperature(const double x, const double y) { return sin(M_PI*y)*cos(2*M_PI*x); }

inline double grad_x_velocity_x(const double x, const double y) { return M_PI*cos(M_PI*x)*cos(M_PI*y); }
inline double grad_y_velocity_x(const double x, const double y) { return -M_PI*sin(M_PI*x)*sin(M_PI*y); }
inline double grad_x_velocity_y(const double x, const double y) { return M_PI*sin(M_PI*x)*sin(M_PI*y); }
inline double grad_y_velocity_y(const double x, const double y) { return -M_PI*cos(M_PI*x)*cos(M_PI*y); }
inline double grad_x_pressure(const double x, const double y) { return -M_PI*sin(M_PI*x)*sin(M_PI*y); }
inline double grad_y_pressure(const double x, const double y) { return M_PI*cos(M_PI*x)*cos(M_PI*y); }
inline double grad_x_temperature(const double x, const double y) { return -2*M_PI*sin(2*M_PI*x)*sin(M_PI*y); }
inline double grad_y_temperature(const double x, const double y) { return M_PI*cos(2*M_PI*x)*cos(M_PI*y); }

inline double momentum_rhs_x(const double x, const double y, const double nu) {
  return M_PI*(2*M_PI*nu*cos(M_PI*y) - sin(M_PI*y) + cos(M_PI*x))*sin(M_PI*x);
}
inline double momentum_rhs_y(const double x, const double y, const double nu) {
  return (1.0/2.0)*M_PI*(2*M_PI*nu*sin(M_PI*(x - y)) - 2*M_PI*nu*sin(M_PI*(x + y)) + sin(2*M_PI*y) + cos(M_PI*(x - y)) + cos(M_PI*(x + y)));
}
inline double continuity_rhs(const double x, const double y) { return 0; }
inline double temperature_rhs(const double x, const double y, const double thermal_diffusivity) {
  return (1.0/2.0)*M_PI*(-20*M_PI*thermal_diffusivity*pow(sin(M_PI*x), 2) + 10*M_PI*thermal_diffusivity - 3*cos(M_PI*x)*cos(M_PI*y) + cos(3*M_PI*x)*cos(M_PI*y))*sin(M_PI*y);
}

} // namespace mms
